// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puzczdcswoxcqfengpbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1emN6ZGNzd294Y3FmZW5ncGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczOTAxNzIsImV4cCI6MjEwMjk2NjE3Mn0.tBXhy-3QRJ9v1HyfDz9zZPSQfEMrTV8k_EozuhOHQ6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});